FROM alpine
ARG APP_VERSION=0.0.1

RUN apk --update --no-cache add curl openjdk8

COPY target/hello-shiftleft-${APP_VERSION}.jar hello-shiftleft.jar

# Install ShiftLeft CLI
RUN curl https://www.shiftleft.io/download/sl-latest-linux-x64.tar.gz | tar xvz -C /usr/local/bin

#RUN sl auth
#COPY config.json /.shiftleft/config.json

# Run ShiftLeft code analysis
EXPOSE 8081
# Run target app with ShiftLeft Microagent
CMD java -jar hello-shiftleft.jar
